# p
# -*- mode: ruby -*-
# vi: set ft=ruby :

#Parse nodes config file
nodes = (JSON.parse(File.read("nodes.json")))

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "centos653"
  #config.vm.box = "centos/7"
  
  nodes.each_with_index do |node, node_index|
    node_name   = node[':node_name'] # name of node
 
    config.vm.define node_name do |config|    
      #Use default SSH private key for every node
      config.ssh.insert_key = false

      config.vm.hostname = node[':hostname']
      config.vm.network :private_network, ip: node[':ip']
      
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", node[':memory']]
        vb.customize ["modifyvm", :id, "--name", node_name]
      end
     
      #Run provisioner at the end, when all nodes are up 
      if node_index == (nodes.size - 1)
        config.vm.provision "ansible" do |ansible|
          #ansible.limit = "all" 
          ansible.playbook = "../site.yml"
          ansible.inventory_path = "../hosts"
          #Disable host key checking so that the hosts don't get added to 
          #our known_hosts file
          ansible.host_key_checking = false
        end
      end

    end
  end
end
